import dotenv from 'dotenv';
import mongoose from 'mongoose';
import fs from 'fs';
import csv from 'csv-parser';
import User from '../src/models/User';
import Camper from '../src/models/Camper';
import logger from '../src/utils/logger';
import path from 'path';

// Load environment variables
dotenv.config();

interface CsvRow {
  'First Name': string;
  'Last Name (Surname)': string;
  'Email': string;
  'Phone Number(WhatsApp Preffered)': string;
  'Gender': string;
  'Are you camping?': string;
  'If yes to the above, What Day will you be coming ?': string;
  'If yes to the above, What Day will you be checking out ?': string;
  'Are you coming as a group or individual?': string;
  'If group how many persons are in your group?': string;
  'If group who is your Bus Marshal/Leader?': string;
  'What city/state do you stay in?': string;
  'What specific location are you coming from?': string;
  [key: string]: string;
}

const isValidEmail = (email: string): boolean => {
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  return emailRegex.test(email);
};

const normalizePhone = (phone: string): string => {
  // Remove all non-digit characters
  return phone.replace(/\D/g, '');
};

const buildNotes = (row: CsvRow): string => {
  const notes: string[] = [];

  if (row['Are you camping?'] && row['Are you camping?'].toLowerCase().includes('yes')) {
    notes.push(`Camping: Yes`);
    if (row['If yes to the above, What Day will you be coming ?']) {
      notes.push(`Arrival: ${row['If yes to the above, What Day will you be coming ?']}`);
    }
    if (row['If yes to the above, What Day will you be checking out ?']) {
      notes.push(`Checkout: ${row['If yes to the above, What Day will you be checking out ?']}`);
    }
  }

  if (row['Are you coming as a group or individual?']) {
    notes.push(`Type: ${row['Are you coming as a group or individual?']}`);
  }

  if (row['If group how many persons are in your group?']) {
    notes.push(`Group Size: ${row['If group how many persons are in your group?']}`);
  }

  if (row['If group who is your Bus Marshal/Leader?']) {
    notes.push(`Leader: ${row['If group who is your Bus Marshal/Leader?']}`);
  }

  if (row['What city/state do you stay in?']) {
    notes.push(`City: ${row['What city/state do you stay in?']}`);
  }

  if (row['What specific location are you coming from?']) {
    notes.push(`Location: ${row['What specific location are you coming from?']}`);
  }

  return notes.join(' | ');
};

const importCampers = async () => {
  try {
    // Connect to MongoDB
    const mongoURI = process.env.MONGODB_URI || 'mongodb://localhost:27017/camp-attendance';
    await mongoose.connect(mongoURI);

    logger.info('Connected to MongoDB');
    console.log('\n Connected to MongoDB\n');

    // Get admin user
    const adminUser = await User.findOne({ email: 'admin@camp.com' });

    if (!adminUser) {
      console.error('L Admin user not found. Please run `npm run seed:admin` first');
      process.exit(1);
    }

    console.log(`=� Using admin user: ${adminUser.email}\n`);

    // Read and parse CSV
    const csvPath = path.join(__dirname, '../registration.csv');
    const rows: CsvRow[] = [];

    await new Promise<void>((resolve, reject) => {
      fs.createReadStream(csvPath)
        .pipe(csv())
        .on('data', (row) => rows.push(row))
        .on('end', () => resolve())
        .on('error', (error) => reject(error));
    });

    console.log(`=� Found ${rows.length} rows in CSV\n`);

    // Delete all existing campers before fresh import
    const existingCount = await Camper.countDocuments();
    if (existingCount > 0) {
      console.log(`⚠️  Deleting ${existingCount} existing camper(s)...\n`);
      await Camper.deleteMany({});
      console.log(`✅ Deleted ${existingCount} existing camper(s)\n`);
    }

    // Process and validate data
    const campersToInsert: any[] = [];
    const errors: any[] = [];
    const duplicates: string[] = [];
    const autogeneratedEmails: string[] = [];
    let autogeneratedEmailCounter = 1;

    for (let i = 0; i < rows.length; i++) {
      const row = rows[i];
      const rowNumber = i + 2; // +2 because CSV has header and arrays are 0-indexed

      // Skip empty rows
      if (!row['First Name'] && !row['Last Name (Surname)'] && !row['Email']) {
        continue;
      }

      // Validate required fields
      if (!row['First Name'] || !row['Last Name (Surname)'] || !row['Email'] || !row['Phone Number(WhatsApp Preffered)']) {
        errors.push({
          row: rowNumber,
          reason: 'Missing required fields',
          data: row,
        });
        continue;
      }

      // Trim fields before validation
      const firstName = row['First Name'].trim();
      const lastName = row['Last Name (Surname)'].trim();
      let email = row['Email'].trim();

      // Validate email (after trimming) - if invalid, generate dummy email
      if (!isValidEmail(email)) {
        // Generate unique dummy email
        const timestamp = Date.now();
        email = `autogenerated-${timestamp}-${autogeneratedEmailCounter}@camp.com`;
        autogeneratedEmailCounter++;
        autogeneratedEmails.push(`Row ${rowNumber}: ${firstName} ${lastName} - Original: "${row['Email']}" → Generated: "${email}"`);
      }

      // Check for duplicates within the CSV itself (using firstName + lastName only)
      const duplicateKey = `${firstName.toLowerCase()}_${lastName.toLowerCase()}`;

      // Check for duplicates within the CSV (by firstName + lastName only)
      if (campersToInsert.some(c =>
        `${c.firstName.toLowerCase()}_${c.lastName.toLowerCase()}` === duplicateKey
      )) {
        duplicates.push(`Row ${rowNumber}: ${firstName} ${lastName} (${email}) - duplicate name in CSV`);
        continue;
      }

      // Normalize gender
      let gender: 'Male' | 'Female' | 'Other' | undefined;
      if (row['Gender']) {
        const genderLower = row['Gender'].toLowerCase();
        if (genderLower.includes('male') && !genderLower.includes('female')) {
          gender = 'Male';
        } else if (genderLower.includes('female')) {
          gender = 'Female';
        } else {
          gender = 'Other';
        }
      }

      // Build camper object
      const camper = {
        firstName,
        lastName,
        email,
        phone: normalizePhone(row['Phone Number(WhatsApp Preffered)']),
        gender,
        status: 'pending',
        notes: buildNotes(row),
        createdBy: adminUser._id,
        updatedBy: adminUser._id,
        isDeleted: false,
      };

      campersToInsert.push(camper);
    }

    // Display summary before import
    console.log('');
    console.log('=� Import Summary');
    console.log('');
    console.log(`Total rows in CSV:       ${rows.length}`);
    console.log(`Valid campers to import: ${campersToInsert.length}`);
    console.log(`Duplicates skipped:      ${duplicates.length}`);
    console.log(`Autogenerated emails:    ${autogeneratedEmails.length}`);
    console.log(`Errors/Invalid rows:     ${errors.length}`);
    console.log('\n');

    if (errors.length > 0) {
      console.log('�  Errors found:');
      errors.slice(0, 10).forEach(err => {
        const emailInfo = err.email ? ` - Email: "${err.email}"` : '';
        console.log(`   Row ${err.row}: ${err.reason}${emailInfo}`);
      });
      if (errors.length > 10) {
        console.log(`   ... and ${errors.length - 10} more errors\n`);
      }
      console.log('');
    }

    if (autogeneratedEmails.length > 0) {
      console.log('⚠️  Autogenerated emails (invalid email format):');
      autogeneratedEmails.slice(0, 10).forEach(entry => {
        console.log(`   ${entry}`);
      });
      if (autogeneratedEmails.length > 10) {
        console.log(`   ... and ${autogeneratedEmails.length - 10} more autogenerated emails\n`);
      }
      console.log('');
    }

    if (duplicates.length > 0) {
      console.log('9  Duplicates skipped:');
      duplicates.slice(0, 10).forEach(dup => {
        console.log(`   ${dup}`);
      });
      if (duplicates.length > 10) {
        console.log(`   ... and ${duplicates.length - 10} more duplicates\n`);
      }
      console.log('');
    }

    if (campersToInsert.length === 0) {
      console.log('L No valid campers to import');
      process.exit(0);
    }

    // Batch insert campers
    console.log(`=� Importing ${campersToInsert.length} campers...\n`);

    const batchSize = 100;
    let imported = 0;
    let duplicateEmails: string[] = [];
    let insertErrors: any[] = [];

    for (let i = 0; i < campersToInsert.length; i += batchSize) {
      const batch = campersToInsert.slice(i, i + batchSize);
      
      try {
        await Camper.insertMany(batch, { ordered: false });
        imported += batch.length;
      } catch (error: any) {
        // Handle bulk write errors (duplicate emails, validation errors, etc.)
        if (error.writeErrors) {
          for (const writeError of error.writeErrors) {
            const failedCamper = batch[writeError.index];
            const errorCode = writeError.err?.code || writeError.code;
            
            // Extract error message from various possible structures
            let errorMsg = '';
            if (writeError.err?.errmsg) {
              errorMsg = writeError.err.errmsg;
            } else if (writeError.errmsg) {
              errorMsg = writeError.errmsg;
            } else if (writeError.err?.message) {
              errorMsg = writeError.err.message;
            } else if (writeError.message) {
              errorMsg = writeError.message;
            } else if (writeError.err?.errors) {
              // Mongoose validation errors
              const validationErrors = Object.values(writeError.err.errors).map((e: any) => e.message).join('; ');
              errorMsg = `Validation error: ${validationErrors}`;
            } else {
              errorMsg = JSON.stringify(writeError.err || writeError);
            }
            
            if (errorCode === 11000) {
              // Duplicate key error (unique email constraint)
              duplicateEmails.push(`${failedCamper.firstName} ${failedCamper.lastName} (${failedCamper.email})`);
            } else {
              insertErrors.push({
                camper: `${failedCamper.firstName} ${failedCamper.lastName}`,
                email: failedCamper.email,
                error: errorMsg,
                code: errorCode,
                fullError: writeError.err || writeError,
              });
            }
          }
          // Count successfully inserted records
          imported += batch.length - error.writeErrors.length;
        } else if (error.errors) {
          // Mongoose validation errors (not bulk write)
          const validationErrors = Object.keys(error.errors).map(key => {
            return `${key}: ${error.errors[key].message}`;
          }).join('; ');
          insertErrors.push({
            batch: `Batch starting at index ${i}`,
            error: `Validation error: ${validationErrors}`,
            fullError: error,
          });
        } else {
          // Other errors - log the full error for debugging
          insertErrors.push({
            batch: `Batch starting at index ${i}`,
            error: error.message || JSON.stringify(error),
            fullError: error,
          });
        }
      }

      const progress = ((imported / campersToInsert.length) * 100).toFixed(1);
      process.stdout.write(`\r   Progress: ${imported}/${campersToInsert.length} (${progress}%)`);
    }

    console.log('\n\n Import completed!\n');
    console.log('');
    console.log('=� Final Statistics');
    console.log('');
    if (duplicateEmails.length > 0) {
      console.log('⚠️  Duplicate emails (skipped during insert):');
      duplicateEmails.slice(0, 10).forEach(dup => {
        console.log(`   ${dup}`);
      });
      if (duplicateEmails.length > 10) {
        console.log(`   ... and ${duplicateEmails.length - 10} more duplicate emails\n`);
      }
      console.log('');
    }

    if (insertErrors.length > 0) {
      console.log('⚠️  Insert errors:');
      insertErrors.slice(0, 10).forEach(err => {
        const errorDetails = err.code ? `[Code: ${err.code}] ` : '';
        const emailInfo = err.email ? ` (${err.email})` : '';
        console.log(`   ${err.camper || err.batch}${emailInfo}: ${errorDetails}${err.error}`);
        // Log full error for first few to help debug
        if (insertErrors.indexOf(err) < 3 && err.fullError) {
          console.log(`      Full error: ${JSON.stringify(err.fullError, null, 2)}`);
        }
      });
      if (insertErrors.length > 10) {
        console.log(`   ... and ${insertErrors.length - 10} more errors\n`);
      }
      console.log('');
    }

    console.log(`Campers imported:        ${imported}`);
    console.log(`Name duplicates skipped: ${duplicates.length}`);
    console.log(`Autogenerated emails:    ${autogeneratedEmails.length}`);
    console.log(`Email duplicates:        ${duplicateEmails.length}`);
    console.log(`Validation errors:       ${errors.length}`);
    console.log(`Insert errors:           ${insertErrors.length}`);
    console.log('\n');

    logger.info('Camper import completed', {
      imported,
      nameDuplicates: duplicates.length,
      autogeneratedEmails: autogeneratedEmails.length,
      emailDuplicates: duplicateEmails.length,
      validationErrors: errors.length,
      insertErrors: insertErrors.length,
    });

    process.exit(0);
  } catch (error) {
    logger.error('Error importing campers:', error);
    console.error('\nL Error importing campers:', error);
    process.exit(1);
  }
};

// Run the script
importCampers();
