import dotenv from 'dotenv';
import mongoose from 'mongoose';
import fs from 'fs';
import csv from 'csv-parser';
import User from '../src/models/User';
import Camper from '../src/models/Camper';
import logger from '../src/utils/logger';
import path from 'path';

// Load environment variables
dotenv.config();

interface CsvRow {
  [key: string]: string;
}

const isValidEmail = (email: string): boolean => {
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  return emailRegex.test(email);
};

const normalizePhone = (phone: string): string => {
  // Remove all non-digit characters
  return phone.replace(/\D/g, '');
};

const normalizeGender = (gender: string): 'Male' | 'Female' | undefined => {
  if (!gender) return undefined;
  const genderLower = gender.toLowerCase();
  if (genderLower.includes('male') && !genderLower.includes('female')) {
    return 'Male';
  } else if (genderLower.includes('female')) {
    return 'Female';
  }
  return undefined;
};

const normalizeBoolean = (value: string): boolean => {
  if (!value) return false;
  return value.trim().toLowerCase() === 'yes';
};

const extractState = (cityState: string): string => {
  if (!cityState) return 'Unknown';
  
  // Handle "Outside Benin" case
  if (cityState.toLowerCase().includes('outside benin')) {
    return 'Outside Benin';
  }
  
  // Try to extract state name
  const stateMatch = cityState.match(/\b(Abia|Adamawa|Akwa Ibom|Anambra|Bauchi|Bayelsa|Benue|Borno|Cross River|Delta|Ebonyi|Edo|Ekiti|Enugu|Gombe|Imo|Jigawa|Kaduna|Kano|Katsina|Kebbi|Kogi|Kwara|Lagos|Nasarawa|Niger|Ogun|Ondo|Osun|Oyo|Plateau|Rivers|Sokoto|Taraba|Yobe|Zamfara|FCT|Abuja)\b/i);
  if (stateMatch) {
    return stateMatch[1];
  }
  
  // Return as-is if no state found
  return cityState.trim() || 'Unknown';
};

const buildNotes = (row: CsvRow): string => {
  const notes: string[] = [];

  if (row['Are you camping?'] && row['Are you camping?'].toLowerCase().includes('yes')) {
    if (row['If yes to the above, What Day will you be coming ?']) {
      notes.push(`Arrival: ${row['If yes to the above, What Day will you be coming ?']}`);
    }
    if (row['If yes to the above, What Day will you be checking out ?']) {
      notes.push(`Checkout: ${row['If yes to the above, What Day will you be checking out ?']}`);
    }
  }

  if (row['Are you coming as a group or individual?']) {
    notes.push(`Type: ${row['Are you coming as a group or individual?']}`);
  }

  if (row['If group how many persons are in your group?']) {
    notes.push(`Group Size: ${row['If group how many persons are in your group?']}`);
  }

  if (row['If group who is your Bus Marshal/Leader?']) {
    notes.push(`Leader: ${row['If group who is your Bus Marshal/Leader?']}`);
  }

  if (row['Are you coming with Children?'] && row['Are you coming with Children?'].toLowerCase() === 'yes') {
    if (row['If yes to the above, please state the number of  children - age - gender?']) {
      notes.push(`Children: ${row['If yes to the above, please state the number of  children - age - gender?']}`);
    }
  }

  if (row['Attendance Option']) {
    notes.push(`Attendance: ${row['Attendance Option']}`);
  }

  if (row['Ticket Number']) {
    notes.push(`Ticket: ${row['Ticket Number']}`);
  }

  return notes.join(' | ');
};

const processCsvFile = async (
  filePath: string,
  isCamping: boolean,
  adminUser: any
): Promise<{ campers: any[]; errors: any[]; duplicates: string[]; autogeneratedEmails: string[] }> => {
  const rows: CsvRow[] = [];
  const campers: any[] = [];
  const errors: any[] = [];
  const duplicates: string[] = [];
  const autogeneratedEmails: string[] = [];
  const seenNames = new Set<string>();
  let autogeneratedEmailCounter = 1;

  // Read CSV file
  await new Promise<void>((resolve, reject) => {
    fs.createReadStream(filePath)
      .pipe(csv())
      .on('data', (row) => rows.push(row))
      .on('end', () => resolve())
      .on('error', (error) => reject(error));
  });

  for (let i = 0; i < rows.length; i++) {
    const row = rows[i];
    const rowNumber = i + 2; // +2 because CSV has header and arrays are 0-indexed

    // Skip empty rows
    if (!row['First Name'] && !row['Last Name (Surname)']) {
      continue;
    }

    // Validate required fields
    if (!row['First Name'] || !row['Last Name (Surname)'] || !row['Phone Number(WhatsApp Preffered)']) {
      errors.push({
        row: rowNumber,
        reason: 'Missing required fields (First Name, Last Name, or Phone)',
        data: row,
      });
      continue;
    }

    // Trim fields
    const firstName = row['First Name'].trim();
    const lastName = row['Last Name (Surname)'].trim();
    let email = row['Email'] ? row['Email'].trim() : '';

    // Check for duplicates by name
    const duplicateKey = `${firstName.toLowerCase()}_${lastName.toLowerCase()}`;
    if (seenNames.has(duplicateKey)) {
      duplicates.push(`Row ${rowNumber}: ${firstName} ${lastName} - duplicate name`);
      continue;
    }
    seenNames.add(duplicateKey);

    // Validate or generate email
    if (!email || !isValidEmail(email)) {
      const timestamp = Date.now();
      email = `autogenerated-${timestamp}-${autogeneratedEmailCounter}@camp.com`;
      autogeneratedEmailCounter++;
      autogeneratedEmails.push(
        `Row ${rowNumber}: ${firstName} ${lastName} - Original: "${row['Email'] || 'N/A'}" → Generated: "${email}"`
      );
    }

    // Extract state
    const cityState = row['What city/state do you stay in?'] || '';
    const state = extractState(cityState);

    // Build camper object
    const camper = {
      firstName,
      lastName,
      email: email.toLowerCase(),
      phone: normalizePhone(row['Phone Number(WhatsApp Preffered)']),
      state,
      subRegion: row['What specific location are you coming from?']?.trim() || undefined,
      gender: normalizeGender(row['Gender']),
      isCamping,
      isHelplineMember: normalizeBoolean(row['Are you a member of Helpline Ministries?']),
      isNyscCorpMember: normalizeBoolean(row['Are you a NYSC Corp Member?']),
      status: 'pending' as const,
      notes: buildNotes(row),
      createdBy: adminUser._id,
      updatedBy: adminUser._id,
      isDeleted: false,
    };

    campers.push(camper);
  }

  return { campers, errors, duplicates, autogeneratedEmails };
};

const insertExtractedCampers = async () => {
  try {
    // Connect to MongoDB
    const mongoURI = process.env.MONGODB_URI || 'mongodb://localhost:27017/camp-attendance';
    await mongoose.connect(mongoURI);

    logger.info('Connected to MongoDB');
    console.log('\n✅ Connected to MongoDB\n');

    // Get admin user
    const adminUser = await User.findOne({ email: 'admin@camp.com' });

    if (!adminUser) {
      console.error('❌ Admin user not found. Please run `npm run seed:admin` first');
      process.exit(1);
    }

    console.log(`✅ Using admin user: ${adminUser.email}\n`);

    // Process campers file
    const campersPath = path.join(__dirname, '../campers_extracted.csv');
    const nonCampersPath = path.join(__dirname, '../non-campers_extracted.csv');

    let allCampers: any[] = [];
    let allErrors: any[] = [];
    let allDuplicates: string[] = [];
    let allAutogeneratedEmails: string[] = [];
    let campersCount = 0;
    let nonCampersCount = 0;

    // Process campers (isCamping = true)
    if (fs.existsSync(campersPath)) {
      console.log('📖 Processing campers_extracted.csv...\n');
      const campersResult = await processCsvFile(campersPath, true, adminUser);
      allCampers.push(...campersResult.campers);
      allErrors.push(...campersResult.errors);
      allDuplicates.push(...campersResult.duplicates);
      allAutogeneratedEmails.push(...campersResult.autogeneratedEmails);
      campersCount = campersResult.campers.length;
      console.log(`✅ Found ${campersCount} campers (isCamping: true)\n`);
    } else {
      console.log('⚠️  campers_extracted.csv not found, skipping...\n');
    }

    // Process non-campers (isCamping = false)
    if (fs.existsSync(nonCampersPath)) {
      console.log('📖 Processing non-campers_extracted.csv...\n');
      const nonCampersResult = await processCsvFile(nonCampersPath, false, adminUser);
      allCampers.push(...nonCampersResult.campers);
      allErrors.push(...nonCampersResult.errors);
      allDuplicates.push(...nonCampersResult.duplicates);
      allAutogeneratedEmails.push(...nonCampersResult.autogeneratedEmails);
      nonCampersCount = nonCampersResult.campers.length;
      console.log(`✅ Found ${nonCampersCount} non-campers (isCamping: false)\n`);
    } else {
      console.log('⚠️  non-campers_extracted.csv not found, skipping...\n');
    }

    // Display summary
    console.log('═══════════════════════════════════════════════════════════');
    console.log('📊 Import Summary');
    console.log('═══════════════════════════════════════════════════════════');
    console.log(`Campers (isCamping: true):    ${campersCount}`);
    console.log(`Non-Campers (isCamping: false): ${nonCampersCount}`);
    console.log(`Total to import:              ${allCampers.length}`);
    console.log(`Duplicates skipped:           ${allDuplicates.length}`);
    console.log(`Autogenerated emails:         ${allAutogeneratedEmails.length}`);
    console.log(`Errors/Invalid rows:          ${allErrors.length}`);
    console.log('═══════════════════════════════════════════════════════════\n');

    if (allErrors.length > 0) {
      console.log('⚠️  Errors found:');
      allErrors.slice(0, 10).forEach((err) => {
        console.log(`   Row ${err.row}: ${err.reason}`);
      });
      if (allErrors.length > 10) {
        console.log(`   ... and ${allErrors.length - 10} more errors\n`);
      }
      console.log('');
    }

    if (allAutogeneratedEmails.length > 0) {
      console.log('⚠️  Autogenerated emails (invalid email format):');
      allAutogeneratedEmails.slice(0, 10).forEach((entry) => {
        console.log(`   ${entry}`);
      });
      if (allAutogeneratedEmails.length > 10) {
        console.log(`   ... and ${allAutogeneratedEmails.length - 10} more autogenerated emails\n`);
      }
      console.log('');
    }

    if (allDuplicates.length > 0) {
      console.log('⚠️  Duplicates skipped:');
      allDuplicates.slice(0, 10).forEach((dup) => {
        console.log(`   ${dup}`);
      });
      if (allDuplicates.length > 10) {
        console.log(`   ... and ${allDuplicates.length - 10} more duplicates\n`);
      }
      console.log('');
    }

    if (allCampers.length === 0) {
      console.log('❌ No valid records to import (campers or non-campers)');
      await mongoose.disconnect();
      process.exit(0);
    }

    // Check for existing campers with same name
    console.log('🔍 Checking for existing campers in database...\n');
    const existingCampers = await Camper.find({
      isDeleted: false,
      $or: allCampers.map((c) => ({
        firstName: { $regex: new RegExp(`^${c.firstName}$`, 'i') },
        lastName: { $regex: new RegExp(`^${c.lastName}$`, 'i') },
      })),
    });

    if (existingCampers.length > 0) {
      console.log(`⚠️  Found ${existingCampers.length} existing camper(s) with matching names:`);
      existingCampers.slice(0, 10).forEach((c) => {
        console.log(`   - ${c.firstName} ${c.lastName} (${c.email})`);
      });
      if (existingCampers.length > 10) {
        console.log(`   ... and ${existingCampers.length - 10} more\n`);
      }
      console.log('\n💡 These will be skipped if they have the same name.\n');
    }

    // Batch insert campers and non-campers
    console.log(`📥 Importing ${allCampers.length} records (${campersCount} campers + ${nonCampersCount} non-campers)...\n`);

    const batchSize = 100;
    let imported = 0;
    let skipped = 0;
    const insertErrors: any[] = [];

    for (let i = 0; i < allCampers.length; i += batchSize) {
      const batch = allCampers.slice(i, i + batchSize);

      try {
        await Camper.insertMany(batch, { ordered: false });
        imported += batch.length;
        process.stdout.write(`\r   Progress: ${imported}/${allCampers.length} imported...`);
      } catch (error: any) {
        // Handle bulk write errors
        if (error.writeErrors) {
          for (const writeError of error.writeErrors) {
            const failedCamper = batch[writeError.index];
            const errorCode = writeError.err?.code || writeError.code;

            if (errorCode === 11000) {
              // Duplicate key error (email or code)
              skipped++;
            } else {
              insertErrors.push({
                name: `${failedCamper.firstName} ${failedCamper.lastName}`,
                error: writeError.err?.message || writeError.message,
              });
            }
          }
          // Count successful inserts from this batch
          imported += batch.length - error.writeErrors.length;
        } else {
          insertErrors.push({
            error: error.message,
          });
        }
        process.stdout.write(`\r   Progress: ${imported}/${allCampers.length} imported...`);
      }
    }

    console.log('\n');

    // Final summary
    console.log('═══════════════════════════════════════════════════════════');
    console.log('✅ Import Complete!');
    console.log('═══════════════════════════════════════════════════════════');
    console.log(`Successfully imported: ${imported}`);
    console.log(`Skipped (duplicates):   ${skipped}`);
    if (insertErrors.length > 0) {
      console.log(`Insert errors:          ${insertErrors.length}`);
    }
    console.log('═══════════════════════════════════════════════════════════\n');

    if (insertErrors.length > 0) {
      console.log('⚠️  Insert errors:');
      insertErrors.slice(0, 10).forEach((err) => {
        console.log(`   ${err.name || 'Unknown'}: ${err.error}`);
      });
      if (insertErrors.length > 10) {
        console.log(`   ... and ${insertErrors.length - 10} more errors\n`);
      }
    }

    await mongoose.disconnect();
    console.log('✅ Disconnected from MongoDB\n');
  } catch (error) {
    console.error('❌ Error inserting campers:', error);
    await mongoose.disconnect();
    process.exit(1);
  }
};

// Run the script
insertExtractedCampers();

